
# API - Microservice

Decription of this microservice

## This documentation [/blueprint]

### Display this documentation [GET]

+ Response 200 (text/html)

## Ping [/ping]

### Check if app is working [GET]

+ Response 200